services:
  server:
    build:
      context: .
      target: dev
    container_name: flow-backend
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  db:
    image: postgres
    container_name: flow-db
    hostname: flow-db
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER" ]
      interval: 2s
      timeout: 1s
      retries: 10
  adminer:
    image: adminer
    container_name: flow-adminer
    ports:
      - 8080:8080

volumes:
  pgdata: {}
